"""add_gta_registration_to_vendor

Revision ID: 3bc5d9e74902
Revises: f9137e67b820
Create Date: 2025-08-03 18:25:00.849895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc5d9e74902'
down_revision = 'f9137e67b820'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_compliance', sa.Column('gta_registration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_compliance', 'gta_registration')
    # ### end Alembic commands ### 