"""Add country_origin and incorporation_certificate_path to vendor model

Revision ID: 4c643fc76384
Revises: 
Create Date: 2025-08-03 14:22:13.409664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c643fc76384'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add columns as nullable
    op.add_column('vendors', sa.Column('country_origin', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('incorporation_certificate_path', sa.String(), nullable=True))
    
    # Update existing records to have a default country_origin value
    op.execute("UPDATE vendors SET country_origin = 'IN' WHERE country_origin IS NULL")
    
    # Now make country_origin NOT NULL
    op.alter_column('vendors', 'country_origin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'incorporation_certificate_path')
    op.drop_column('vendors', 'country_origin')
    # ### end Alembic commands ### 