"""add_vendor_agreement_details_table

Revision ID: 648c122189ce
Revises: e52308586217
Create Date: 2025-08-07 17:12:34.219083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648c122189ce'
down_revision = 'e52308586217'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 