"""add_all_vendor_fields_to_main_table

Revision ID: 66d836866b76
Revises: 3bc5d9e74902
Create Date: 2025-08-04 10:35:37.224441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d836866b76'
down_revision = '3bc5d9e74902'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('registered_address', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('registered_city', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('registered_state', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('registered_country', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('registered_pincode', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('supply_address', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('supply_city', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('supply_state', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('supply_country', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('supply_pincode', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('account_number', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('account_type', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('ifsc_code', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('branch_name', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('pan_number', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('gst_number', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('preferred_currency', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('tax_registration_number', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('vat_number', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('business_license', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('gta_registration', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('compliance_notes', sa.Text(), nullable=True))
    op.add_column('vendors', sa.Column('credit_rating', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('insurance_coverage', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('special_certifications', sa.Text(), nullable=True))
    op.add_column('vendors', sa.Column('nda', sa.Boolean(), nullable=True))
    op.add_column('vendors', sa.Column('sqa', sa.Boolean(), nullable=True))
    op.add_column('vendors', sa.Column('four_m', sa.Boolean(), nullable=True))
    op.add_column('vendors', sa.Column('code_of_conduct', sa.Boolean(), nullable=True))
    op.add_column('vendors', sa.Column('compliance_agreement', sa.Boolean(), nullable=True))
    op.add_column('vendors', sa.Column('self_declaration', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'self_declaration')
    op.drop_column('vendors', 'compliance_agreement')
    op.drop_column('vendors', 'code_of_conduct')
    op.drop_column('vendors', 'four_m')
    op.drop_column('vendors', 'sqa')
    op.drop_column('vendors', 'nda')
    op.drop_column('vendors', 'special_certifications')
    op.drop_column('vendors', 'insurance_coverage')
    op.drop_column('vendors', 'credit_rating')
    op.drop_column('vendors', 'compliance_notes')
    op.drop_column('vendors', 'gta_registration')
    op.drop_column('vendors', 'business_license')
    op.drop_column('vendors', 'vat_number')
    op.drop_column('vendors', 'tax_registration_number')
    op.drop_column('vendors', 'preferred_currency')
    op.drop_column('vendors', 'gst_number')
    op.drop_column('vendors', 'pan_number')
    op.drop_column('vendors', 'currency')
    op.drop_column('vendors', 'branch_name')
    op.drop_column('vendors', 'ifsc_code')
    op.drop_column('vendors', 'account_type')
    op.drop_column('vendors', 'account_number')
    op.drop_column('vendors', 'bank_name')
    op.drop_column('vendors', 'supply_pincode')
    op.drop_column('vendors', 'supply_country')
    op.drop_column('vendors', 'supply_state')
    op.drop_column('vendors', 'supply_city')
    op.drop_column('vendors', 'supply_address')
    op.drop_column('vendors', 'registered_pincode')
    op.drop_column('vendors', 'registered_country')
    op.drop_column('vendors', 'registered_state')
    op.drop_column('vendors', 'registered_city')
    op.drop_column('vendors', 'registered_address')
    # ### end Alembic commands ### 