"""add_vendor_compliance_certificates_table

Revision ID: 796bad7bd004
Revises: 66d836866b76
Create Date: 2025-08-07 16:33:28.996771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796bad7bd004'
down_revision = '66d836866b76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 