"""add_vendor_compliance_certificates_table

Revision ID: c40710d20ad9
Revises: 796bad7bd004
Create Date: 2025-08-07 16:42:38.518229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40710d20ad9'
down_revision = '796bad7bd004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 