"""Add incorporation_certificate to DocumentType enum

Revision ID: dc55a17fd01f
Revises: 4c643fc76384
Create Date: 2025-08-03 14:27:06.536170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc55a17fd01f'
down_revision = '4c643fc76384'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 