"""add_vendor_compliance_certificates_table_with_unique_constraint

Revision ID: e52308586217
Revises: c40710d20ad9
Create Date: 2025-08-07 16:47:45.797931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52308586217'
down_revision = 'c40710d20ad9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_vendor_certificate_number', 'vendor_compliance_certificates', ['vendor_id', 'certificate_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vendor_certificate_number', 'vendor_compliance_certificates', type_='unique')
    # ### end Alembic commands ### 