"""add_msme_category_to_vendor

Revision ID: f9137e67b820
Revises: dc55a17fd01f
Create Date: 2025-08-03 17:08:24.061068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9137e67b820'
down_revision = 'dc55a17fd01f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('msme_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'msme_category')
    # ### end Alembic commands ### 